extends: default

ignore: |
  .github/workflows/*

rules:
  line-length:
    max: 140
    level: error

  indentation:
    spaces: consistent
    indent-sequences: consistent

  document-start:
    present: false

  comments:
    require-starting-space: true

  trailing-spaces:
    level: warning

  new-lines: disable

  truthy:
    allowed-values: ["true", "false"]

  colons:
    max-spaces-before: 0
    max-spaces-after: 1
