extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: consistent
    indent-sequences: consistent

  document-start:
    present: false

  comments:
    require-starting-space: true

  trailing-spaces:
    level: warning

  new-lines:
    type: unix

  truthy:
    allowed-values: ['true', 'false']

  colons:
    max-spaces-before: 0
    max-spaces-after: 1
