# Generated by Django 4.2.23 on 2025-06-26 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arc_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("day_count", models.PositiveIntegerField()),
                ("liturgical_fit", models.CharField(blank=True, max_length=255)),
                ("journey_stage", models.CharField(blank=True, max_length=255)),
                ("anchor_image", models.TextField(blank=True)),
                ("primary_reading_title", models.CharField(blank=True, max_length=255)),
                (
                    "primary_reading_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                ("primary_reading_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeditationDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField(unique=True)),
                ("arc_day", models.PositiveIntegerField()),
                ("anchor_image", models.TextField(blank=True)),
                ("primary_reading_title", models.CharField(blank=True, max_length=255)),
                (
                    "primary_reading_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                ("primary_reading_url", models.URLField(blank=True)),
                ("meditative_point_1", models.TextField()),
                ("meditative_point_2", models.TextField(blank=True)),
                ("meditative_point_3", models.TextField(blank=True)),
                ("ejaculatory_prayer", models.TextField()),
                ("colloquy", models.TextField()),
                ("resolution", models.TextField(blank=True)),
                (
                    "arc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.arc"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("doctrinal", "Doctrinal"),
                            ("virtue", "Virtue"),
                            ("mystical", "Mystical"),
                            ("liturgical", "Liturgical"),
                            ("typological", "Typological"),
                            ("thematic", "Thematic"),
                            ("structural", "Structural"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecondaryReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_readings",
                        to="website.meditationday",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DayTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.meditationday",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArcTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.arc"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.tag"
                    ),
                ),
            ],
        ),
    ]
