# Generated by Django 4.2.23 on 2025-06-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meditationday",
            name="meditative_point_2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meditationday",
            name="meditative_point_3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meditationday",
            name="primary_reading_reference",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meditationday",
            name="primary_reading_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
