# Generated by Django 4.2.23 on 2025-07-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_meditationday_meditative_point_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arc",
            name="arc_summary",
            field=models.TextField(default="No summary yet."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="arc",
            name="card_tags",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of tag names"
            ),
        ),
    ]
