# Generated by Django 4.2.23 on 2025-07-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_arc_arc_summary_arc_card_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arc",
            name="card_tags",
            field=models.JSONField(default=list),
        ),
    ]
