# Generated by Django 4.2.23 on 2025-07-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_arc_card_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arc",
            name="card_tags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
