# Generated by Django 4.2.23 on 2025-07-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_arc_card_tags"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meditationday",
            unique_together={("arc", "arc_day_number")},
        ),
    ]
