# Generated by Django 4.2.23 on 2025-07-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_meditationday_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arc",
            name="anchor_image",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="arc",
            name="primary_reading",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
