# Generated by Django 4.2.23 on 2025-07-11 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0008_alter_arc_anchor_image_alter_arc_primary_reading"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserJourney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="My Journey with Ignation Mental Prayer", max_length=255
                    ),
                ),
                ("arc_progress", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
