# Generated by Django 4.2.23 on 2025-07-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_userjourney"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserJourneyArcProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arc_id", models.CharField(max_length=100)),
                ("arc_title", models.CharField(max_length=255)),
                ("day_count", models.PositiveIntegerField(default=1)),
                ("current_day", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("upcoming", "Upcoming"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "user_journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arc_progress_items",
                        to="website.userjourney",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("user_journey", "arc_id")},
            },
        ),
    ]
