# Generated by Django 4.2.23 on 2025-07-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_userjourneyarcprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userjourney",
            name="arc_progress",
        ),
    ]
