# Generated by Django 4.2.23 on 2025-07-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_remove_userjourney_arc_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="userjourney",
            name="completed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userjourney",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
