# Generated by Django 4.2.23 on 2025-07-14 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_alter_userjourney_completed_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="userjourney",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
