# Generated by Django 4.2.23 on 2025-07-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_userjourney_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userjourney",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
