# Generated by Django 4.2.23 on 2025-07-14 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0015_userjourney_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userjourney",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journeys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
