# Generated by Django 4.2.23 on 2025-07-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_alter_userjourney_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userjourneyarcprogress",
            name="skipped",
            field=models.BooleanField(default=False),
        ),
    ]
