# Generated by Django 4.2.23 on 2025-07-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_userjourneyarcprogress_skipped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userjourneyarcprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("upcoming", "Upcoming"),
                    ("completed", "Completed"),
                    ("skipped", "Skipped"),
                ],
                max_length=20,
            ),
        ),
    ]
