# Generated by Django 4.2.23 on 2025-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_alter_userjourneyarcprogress_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userjourney",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
    ]
