# Generated by Django 4.2.23 on 2025-08-19 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0020_meditationnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("session", models.CharField(blank=True, max_length=64)),
                ("path", models.TextField()),
                ("query", models.TextField(blank=True)),
                ("referrer", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ua", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ts"], name="website_pag_ts_f46129_idx"),
                    models.Index(
                        fields=["country"], name="website_pag_country_016f58_idx"
                    ),
                ],
            },
        ),
    ]
