# Generated by Django 4.2.23 on 2025-08-19 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0021_pageview"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pageview",
            name="website_pag_ts_f46129_idx",
        ),
        migrations.RemoveIndex(
            model_name="pageview",
            name="website_pag_country_016f58_idx",
        ),
        migrations.RenameField(
            model_name="pageview",
            old_name="ts",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="pageview",
            old_name="query",
            new_name="user_agent",
        ),
        migrations.RemoveField(
            model_name="pageview",
            name="country",
        ),
        migrations.RemoveField(
            model_name="pageview",
            name="session",
        ),
        migrations.RemoveField(
            model_name="pageview",
            name="ua",
        ),
        migrations.AddField(
            model_name="pageview",
            name="screen_h",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pageview",
            name="screen_w",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pageview",
            name="title",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="pageview",
            name="tz",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="pageview",
            name="visitor_id",
            field=models.CharField(db_index=True, default="default", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pageview",
            name="path",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="referrer",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pageviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["created_at"], name="website_pag_created_6b7b7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(fields=["path"], name="website_pag_path_3c2507_idx"),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["visitor_id", "created_at"],
                name="website_pag_visitor_87a7e3_idx",
            ),
        ),
    ]
