const tagDescriptions: Record<string, Record<string, string>> = {
  // Theological truths and teachings of the Catholic faith.
  // These meditations focus on the core beliefs and doctrines that shape the Christian life.
  doctrinal: {
    "absolution": "The act by which a priest, in the person of Christ, forgives sins in the Sacrament of Penance.",
    "apostolic authority": "The divine authority given by Christ to the Apostles and their successors to teach, govern, and sanctify.",
    "atonement": "Christ’s satisfaction for sin through His Passion, restoring man to communion with God.",
    "baptism": "The first sacrament of initiation that cleanses from original sin and makes one a child of God.",
    "catechism": "A summary of Catholic doctrine used for teaching and formation in the faith.",
    "christ's humanity and divinity": "The mystery that Jesus Christ is fully God and fully man in one divine Person.",
    "christology": "The theological study of the Person, nature, and mission of Jesus Christ.",
    "church": "The Body of Christ — a visible and spiritual communion instituted by Christ and governed by the successors of the Apostles.",
    "commandments": "The divine laws given by God, especially the Ten Commandments, as guides to moral living.",
    "communion": "Union with Christ and His Church, especially through the Eucharist.",
    "concupiscence": "The inclination to sin that remains after Baptism due to the wounds of original sin.",
    "confession": "The act of acknowledging one’s sins aloud in the Sacrament of Penance for absolution.",
    "conviction": "The inner acknowledgment of truth, often awakened by grace to repentance or belief.",
    "corporal works": "Charitable acts that meet the physical needs of others, such as feeding the hungry and clothing the naked.",
    "damnation": "The eternal separation from God incurred through unrepented mortal sin.",
    "deus absconditus": "The 'hidden God' — a theme in theology emphasizing God's mysterious ways and His veiling of glory.",
    "dignity of the human person": "The inherent worth of every person created in the image of God.",
    "devotion to the heart of jesus": "Loving reverence for the Sacred Heart as a symbol of Christ’s divine love and mercy.",
    "divine mysteries": "Truths revealed by God that surpass human understanding, such as the Trinity or Incarnation.",
    "ecclesiology": "The theological study of the Church’s nature, structure, and mission.",
    "eschatology": "The study of the last things: death, judgment, heaven, hell, and the second coming.",
    "eucharist": "The true Body, Blood, Soul, and Divinity of Jesus Christ, offered and received in the Mass.",
    "general judgment": "The final judgment of all souls by Christ at the end of time, revealing every deed.",
    "grace": "The free and undeserved gift of God’s life and help to become holy and reach heaven.",
    "hell": "The eternal state of separation from God for those who freely reject His mercy.",
    "hypostatic union": "The union of Christ’s divine and human natures in the one Person of the Son.",
    "immaculate heart": "Mary’s pure and loving heart, full of grace and united perfectly with God’s will.",
    "incarnation": "The mystery of God the Son becoming man in the womb of the Virgin Mary.",
    "joy in suffering": "The paradoxical grace of rejoicing in trials because of union with Christ’s Cross.",
    "judgment": "God’s definitive evaluation of each soul’s life and response to grace.",
    "justice of God": "The perfect moral order and holiness by which God gives each their due.",
    "kingship of christ": "Christ’s authority over all creation as divine Lord and Savior.",
    "love of god": "The central commandment and highest vocation of man: to love God with all one’s heart.",
    "mary": "The Mother of God, sinless and full of grace, model of discipleship and Queen of Heaven.",
    "mary as co-redemptrix": "Mary’s unique participation in Christ’s redemptive mission through her fiat and sufferings.",
    "maternal sacrifice": "Mary’s loving offering of her Son for our salvation, especially at the foot of the Cross.",
    "mediation": "The act of interceding between God and man, fulfilled supremely by Christ and, in a subordinate way, by Mary and the saints.",
    "merit": "The reward due to good actions done in grace, cooperating with God’s will.",
    "mother of the church": "Title of Mary as spiritual Mother to all Christians and Mother of the Church.",
    "mystical body": "The Church as the living Body of Christ, composed of all the baptized in union with Him.",
    "new commandment": "Christ’s command to love one another as He has loved us — even unto death.",
    "paschal mystery": "Christ’s Passion, Death, Resurrection, and Ascension — the center of salvation history.",
    "passion": "The suffering and death of Jesus, by which He redeemed mankind.",
    "poverty of christ": "The voluntary renunciation of earthly glory and riches by Jesus for our sake.",
    "reconciliation": "The restoration of friendship with God through the forgiveness of sins.",
    "redemption": "Christ’s act of saving mankind from sin by His sacrifice on the Cross.",
    "repentance": "A turning away from sin and turning toward God with sorrow and conversion of heart.",
    "reverence": "A holy respect and awe before God, His mysteries, and His sacred things.",
    "sacred heart": "A symbol of Christ’s divine love, wounded for us and burning with mercy.",
    "sacrament of penance": "The sacrament by which sins committed after Baptism are forgiven through priestly absolution.",
    "salvation": "The deliverance from sin and its consequences through Christ’s grace and sacrifice.",
    "sanctification": "The process of becoming holy by cooperating with God’s grace.",
    "sanctifying grace": "The habitual gift that makes the soul holy and pleasing to God.",
    "second coming": "The glorious return of Christ to judge the living and the dead.",
    "sin": "A deliberate offense against God’s law, either venial (weakening grace) or mortal (destroying it).",
    "sonship of christ": "Jesus’ eternal identity as the Son of God, consubstantial with the Father.",
    "soteriology": "The branch of theology concerned with salvation through Christ.",
    "spiritual rest": "The peace of soul given by God when one lives in His will and grace.",
    "suffering servant": "Isaiah’s prophecy fulfilled in Christ, who bore our sins in meekness and love.",
    "trinity": "The central mystery of one God in three divine Persons: Father, Son, and Holy Spirit.",
    "truth": "The conformity of intellect to reality, supremely found in Christ who is the Truth incarnate.",
    "virtues": "Stable dispositions to do the good, infused by God and cultivated through grace.",
    "vocation": "The divine call to holiness through a particular state in life: marriage, consecrated life, or priesthood.",
    "wisdom": "The gift of seeing all things in the light of God and ordering life accordingly.",
    "works of mercy": "Actions of love that care for the spiritual and bodily needs of others.",
    "worship": "The adoration due to God alone, especially through the liturgy and prayer.",
  },

  // Mystical and contemplative themes.
  // These meditations focus on the inner life of prayer, union with God, and the mystical dimensions of faith.
  mystical: {
    "adoration": "Interior worship and silent gaze upon God with reverence and awe.",
    "compunction": "Interior sorrow for sin and desire for conversion.",
    "mystical union": "Themes of deep union with God through prayer and love.",
    "divine intimacy": "Closeness to God cultivated through contemplative prayer.",
    "abiding in love": "Remaining in intimate union with Christ, allowing His love to dwell continuously in the soul.",
    "awe": "A deep reverence and wonder before God's majesty and holiness.",
    "beatific vision": "The direct vision of God in Heaven, the ultimate fulfillment of the soul.",
    "body of christ": "The mystical union of all believers with Christ as Head, particularly in the Eucharist and the Church.",
    "christ in the poor": "The mystical presence of Christ in the suffering and marginalized.",
    "contemplation": "A silent, loving gaze upon God — the highest form of prayer, often infused by grace.",
    "darkness": "A state of spiritual obscurity that can purify the soul, also called the ‘dark night.’",
    "divine adoption": "The mystery of being made true sons and daughters of God through grace.",
    "divine advocacy": "Christ and the Holy Spirit interceding for us before the Father, guiding and defending the soul.",
    "divine charity": "The supernatural love of God, poured into the heart by the Holy Spirit.",
    "divine condescension": "God's loving descent to meet man where he is — seen most fully in the Incarnation and the Cross.",
    "divine discernment": "The grace to see and choose according to God’s will, beyond natural reasoning.",
    "divine hiddenness": "God’s mysterious presence, often veiled from human perception but deeply real.",
    "divine image": "The imprint of God's nature in the human soul, calling it to reflect His holiness.",
    "divine indwelling": "The Trinity’s presence within the soul in the state of grace.",
    "divine initiative": "God always acts first in love, calling the soul before it seeks Him.",
    "divine love": "The infinite, self-giving love of God — source of all true charity.",
    "divine majesty": "The glory and grandeur of God, adored by angels and saints.",
    "divine mercy": "God’s loving response to human misery, healing and forgiving.",
    "divine nourishment": "The grace, especially in the Eucharist, that feeds and strengthens the soul.",
    "divine physician": "Christ as healer of both body and soul, restoring through mercy.",
    "divine presence": "God’s nearness, both hidden and manifest — in the soul, the sacraments, and creation.",
    "divine silence": "God’s wordless communication — a trial, invitation, or sign of deeper intimacy.",
    "divine will": "God’s perfect and loving plan for each soul, to be sought and embraced.",
    "docility": "A soul’s openness and responsiveness to the movements of the Holy Spirit.",
    "healing": "The inner restoration of the soul through divine grace and mercy.",
    "heaven": "The state of perfect union with God, fulfillment of every desire.",
    "heavenly consummation": "The final and complete union of the soul with God at the end of time.",
    "heavenly liturgy": "The eternal worship of God in Heaven, mirrored in the Church’s liturgy on earth.",
    "heavenly mediation": "The intercession of Christ, Mary, and the saints before the throne of God.",
    "heavenly worship": "The praise of God by the angels and saints — perfect adoration.",
    "hidden acts": "Interior or unnoticed acts of virtue done for God alone.",
    "holy of holies": "The innermost sanctuary — now fulfilled in Christ and the soul in grace.",
    "inheritance": "The eternal life and glory promised to God’s children.",
    "inner watchfulness": "A vigilant heart attuned to the voice and presence of God.",
    "intercession": "Praying on behalf of others — a powerful act of love and spiritual solidarity.",
    "interior cleansing": "The purification of the soul from attachments and sin, often through trial.",
    "light": "A symbol of grace, truth, and divine guidance.",
    "longing for union": "The deep desire of the soul to be one with Christ.",
    "marian companionship": "Walking the spiritual path in closeness with Mary as model and guide.",
    "mortification": "Voluntary self-denial to conform the soul more closely to Christ.",
    "mystery": "Divine realities beyond full human understanding, revealed in faith.",
    "mystery of redemptive silence": "Christ’s silent suffering — a profound expression of love and obedience.",
    "overshadowing": "The Spirit’s gentle covering — as in the Annunciation — signaling God’s initiative.",
    "pierced heart": "The suffering and love of Christ (or Mary), expressed through the heart wounded by love.",
    "praise": "Joyful glorification of God, especially in recognition of His goodness and mercy.",
    "purification": "The process by which the soul is cleansed and made ready for deeper union with God.",
    "royal priesthood": "The baptized sharing in Christ’s priestly mission — offering their lives to God.",
    "separation from God": "The soul’s greatest suffering — either in sin or the purgative journey.",
    "silence": "Both exterior and interior quiet, creating space for God’s presence.",
    "spiritual childhood": "Total trust, humility, and simplicity before the Father — the Little Way.",
    "spiritual darkness": "A trial of the soul — often leading to greater faith and union.",
    "spiritual enthronement": "Christ reigning in the heart — the soul as His temple.",
    "spiritual homecoming": "The soul’s return to God through repentance and grace.",
    "spiritual identity": "The soul’s truest self — found only in relation to God.",
    "spiritual maternity": "Mary’s maternal role in the soul’s formation — or the call to spiritual nurture.",
    "spiritual priesthood": "The offering of one’s life, works, and prayers in union with Christ.",
    "spiritual warfare": "The interior battle against sin, temptation, and spiritual deception.",
    "sorrow": "Holy sorrow — especially for sin — opens the soul to mercy and transformation.",
    "thirst": "Christ’s thirst for souls — and the soul’s thirst for Him.",
    "union": "The goal of the spiritual life — perfect intimacy with God.",
    "union with christ": "The soul’s transformation through grace into Christ’s likeness.",
    "union with mary": "Walking in deep unity with Mary — sharing her heart, virtues, and mission.",
    "waiting": "Holy patience — trusting God’s timing in silence and faith.",
    "washing of feet": "A mystical symbol of service, humility, and purification.",
    "wounded love": "Christ’s love wounded by rejection — yet burning still with mercy.",
  },

  // Thematic meditations that explore various aspects of the Christian life.
  // These themes are often broad and can encompass doctrinal, mystical, and practical dimensions.
  thematic: {
    "abandonment": "The act of surrendering oneself entirely to God's providence, even in times of desolation.",
    "action": "A call to live out the faith actively in the world through works of charity and mercy.",
    "adoration": "Loving reverence directed to God alone, especially in response to His presence and majesty.",
    "baptismal identity": "Our foundational identity as children of God, conferred through the sacrament of Baptism.",
    "betrayal": "The experience of being abandoned or denied, particularly echoing the Passion of Christ.",
    "betrayal and fidelity": "A contrast between human unfaithfulness and divine steadfastness.",
    "birth of the church": "The moment of the Church's origin, particularly through the side of Christ and at Pentecost.",
    "blood of christ": "The precious blood poured out in the Passion, source of redemption and divine life.",
    "bondage and freedom": "The dynamic between slavery to sin and the freedom found in Christ.",
    "burial": "Meditation on Christ's rest in the tomb, a sign of His full entrance into death.",
    "captivity of sin": "The soul's bondage under sin and the need for divine liberation.",
    "christ the high priest": "Christ as the mediator between God and man, offering the perfect sacrifice.",
    "confidence in prayer": "Trust in God's goodness and fatherhood when approaching Him in prayer.",
    "conversion": "The turning of the soul back to God through grace and repentance.",
    "contrition": "True sorrow for sin arising from love of God above all else.",
    "cross": "The central symbol of salvation and self-emptying love in the Christian life.",
    "crucifixion": "A meditation on Christ nailed to the Cross — the summit of His redemptive suffering.",
    "damnation": "Eternal separation from God; a reality that underscores the urgency of salvation.",
    "death": "Both physical and spiritual death, now transformed by Christ’s Resurrection.",
    "desire": "The longing of the heart, often restless until it rests in God.",
    "desire for god": "A deep yearning for intimacy and union with the Creator.",
    "desire for union with christ": "A longing to be one with the suffering and glorified Lord.",
    "discipleship": "The radical following of Christ in all things, especially through the Cross.",
    "eternal reward": "The promise of beatitude for those who remain faithful.",
    "eternal worship": "Heavenly praise of the Trinity in which the soul is invited to participate.",
    "fear of the lord": "A reverent awe before God’s majesty, justice, and love — a gift of the Holy Spirit.",
    "final judgment": "The moment when all will be revealed and souls judged by Christ.",
    "finding in the temple": "The mystery of Christ’s wisdom and obedience, even as a child.",
    "gift of self": "Total self-donation, modeled on Christ’s sacrificial love.",
    "glory of christ": "The radiant majesty of Christ, hidden in suffering and revealed in resurrection.",
    "heart of christ": "The center of Christ’s love, pierced for our redemption.",
    "heaven": "The soul’s final union with God — eternal life in perfect love.",
    "hell": "Eternal separation from God chosen by unrepentant sin — a mystery of justice and sorrow.",
    "humiliation": "Christ’s voluntary abasement and the call to embrace lowliness for love.",
    "identity": "The soul’s truest self as known and loved by God.",
    "injustice": "The wounds of sin in the world and Christ’s response through mercy.",
    "interior agony": "The spiritual suffering of Christ and the soul that participates in His Passion.",
    "interior battle": "The conflict within the heart between grace and temptation.",
    "invitation to trust": "God’s persistent call to surrender fear and rely on His love.",
    "judgment": "God’s definitive word on each soul — merciful and just.",
    "kingship": "Christ’s reign over all creation, manifest in meekness and majesty.",
    "lamb of god": "The sacrificial identity of Christ as foretold and fulfilled.",
    "last things": "Death, judgment, heaven, and hell — the four final realities of every soul.",
    "light and darkness": "Spiritual illumination versus ignorance and sin.",
    "love of god": "The foundation of all things — God’s love poured into our hearts.",
    "love of jesus": "Affective devotion and attachment to the person of Christ.",
    "love of neighbor": "The second great commandment — inseparable from love of God.",
    "loving response": "The soul’s return of love to the One who loved first.",
    "magnificat": "Mary’s canticle of praise — a model of humility and joy in God.",
    "mary": "The Mother of God, perfect model of discipleship and trust.",
    "mercy": "God’s love poured out on the miserable — the heart of the Gospel.",
    "mercy in suffering": "God’s nearness and tenderness amid affliction.",
    "mockery": "Christ endured ridicule and contempt — a call to humility.",
    "mortal sin": "A grave rejection of God that kills the life of grace in the soul.",
    "motherhood": "Mary’s spiritual motherhood and the Church’s maternal care.",
    "obedience unto death": "Christ’s surrender to the Father — even to the Cross.",
    "origin of charity": "The love of God, revealed and poured into hearts through Christ.",
    "passion of christ": "The suffering of Jesus from Gethsemane to Calvary — the price of our redemption.",
    "peace": "The fruit of union with God, even in tribulation.",
    "presence": "God’s nearness — in the Eucharist, in the heart, in suffering.",
    "priesthood of the faithful": "The baptized called to offer spiritual sacrifices through Christ.",
    "redemptive suffering": "Pain united to Christ’s Passion becomes a source of grace.",
    "reparation": "Acts of love and sacrifice offered to console and honor the Heart of Jesus.",
    "return to the father": "The prodigal journey back to God’s merciful embrace.",
    "rosary": "A powerful meditative prayer rooted in Scripture and love of Mary.",
    "sacred heart": "The burning, wounded love of Christ — visible in His Heart.",
    "sacraments": "Visible signs instituted by Christ to confer grace.",
    "sacrifice": "The offering of oneself in love — perfected in Christ and lived by His members.",
    "sacrificial love": "Love that gives all, even unto death — Christ’s love on the Cross.",
    "salvation": "The gift of eternal life offered through Christ’s Passion and Resurrection.",
    "salvation through the cross": "The paradox of glory through suffering — the means of redemption.",
    "sanctuary": "The sacred place of God’s presence, especially in the heart and the Eucharist.",
    "silence of god": "God’s mysterious quiet in suffering — an invitation to deeper trust.",
    "suffering": "A mystery touched by grace and transformed in union with Christ.",
    "tenderness": "The gentle, loving approach of God to wounded souls.",
    "transformation": "The soul’s gradual change through grace into the likeness of Christ.",
    "transforming grace": "The power of divine life that heals, elevates, and divinizes.",
    "unity": "The communion of believers — with Christ, with one another, with the Church.",
    "witness": "Public fidelity to Christ — in word, deed, and suffering.",
    "wound of sin": "The damage sin does to the soul, healed by mercy and grace.",
  },

  // Virtue and moral themes.
  // These meditations focus on the cultivation of virtues and the moral life in Christ.
  virtue: {
    "acts of mercy": "Concrete actions of compassion and charity toward others, especially the suffering.",
    "apostolic courage": "Boldness and perseverance in bearing witness to Christ, even amidst adversity.",
    "chastity": "The virtue that orders sexual desire toward love and purity according to one's state in life.",
    "charity": "Supernatural love of God and neighbor, the greatest of the theological virtues.",
    "communion": "Living in unity with God and others through love, humility, and shared grace.",
    "contrition": "Sincere sorrow for sin, arising from love of God and desire for reconciliation.",
    "courage": "Firmness of spirit to do the good despite fear, difficulty, or suffering.",
    "detachment": "Interior freedom from created things, so as to love and serve God above all.",
    "diligence": "Steady, faithful effort in one’s duties and in the pursuit of virtue.",
    "docility": "Willingness to be taught and led, especially by the Holy Spirit or lawful authority.",
    "faith": "Belief in God and all He has revealed, trusting in His promises.",
    "faithfulness": "Steadfastness in love, truth, and duty, especially in one's vocation or commitments.",
    "fortitude": "Moral strength to endure trial and resist temptation for the sake of the good.",
    "gentleness": "The virtue of meekness, humility, and calm strength in dealing with others.",
    "gratitude": "A thankful heart that acknowledges all gifts as coming from God.",
    "hope": "Confident expectation of divine help and eternal life, even amid darkness.",
    "humility": "Truthful lowliness before God, acknowledging one’s dependence and nothingness apart from grace.",
    "justice": "Giving each their due — to God in worship, and to neighbor in fairness and respect.",
    "longsuffering": "Patient endurance of hardship or offense without resentment or complaint.",
    "meekness": "Quiet strength that restrains anger and embraces peacefulness.",
    "mercy": "Loving compassion shown to those in misery, flowing from the heart of God.",
    "obedience": "Submitting to the will of God and lawful authority out of love and faith.",
    "patience": "Enduring suffering, delay, or difficulty with trust and peace.",
    "penitence": "Interior sorrow for sin, often expressed in prayer, fasting, or works of reparation.",
    "perseverance": "Remaining firm in faith and virtue until the end, trusting God’s grace.",
    "poverty of spirit": "Inner freedom from attachment to possessions, trusting fully in God’s providence.",
    "prayerfulness": "A heart attuned to God through regular, sincere, and humble prayer.",
    "purity of heart": "A single-hearted love for God that excludes all impurity and disordered desire.",
    "repentance": "Turning away from sin and toward God with sincere conversion of heart.",
    "restitution": "Making amends for wrongs committed, especially through acts of justice and charity.",
    "self-denial": "Choosing to forgo legitimate goods to grow in holiness and love.",
    "self-forgetfulness": "Freedom from self-centeredness, allowing one to focus entirely on God and others.",
    "silence": "Interior and exterior stillness that fosters recollection, humility, and attentiveness to God.",
    "surrender": "Total trustful abandonment of oneself into the hands of God.",
    "temperance": "Moderation and self-control in all pleasures, directing them according to reason and grace.",
    "trust": "Placing one’s confidence in God’s goodness, providence, and mercy.",
    "virtue of tears": "Holy sorrow for sin or for the suffering of Christ and others, often expressed in weeping.",
    "vulnerability": "Courageous openness in love, embracing weakness in order to receive and give grace.",
    "zeal": "Fervent love for God that drives one to act, evangelize, and sacrifice generously.",
  },

  // Liturgical seasons and feasts.
  // These meditations are tied to the Church's liturgical calendar, focusing on specific seasons
  liturgical: {
    "lent": "Themes of repentance, fasting, and preparation for Easter.",
    "easter": "Joyful celebration of the Resurrection and its effects on the soul.",
    "adoration": "The worship of God in the Blessed Sacrament, acknowledging His real presence and majesty.",
    "angelus": "A Marian devotion recalling the Incarnation, traditionally prayed morning, noon, and evening.",
    "anima christi": "A beloved Eucharistic prayer asking Jesus for purification, protection, and union with Him.",
    "ave maria": "The Hail Mary prayer, honoring the Virgin Mary and asking for her intercession.",
    "benediction": "A liturgical blessing with the Eucharist, often following a time of adoration.",
    "corpus christi": "The feast celebrating the Real Presence of Christ in the Eucharist.",
    "devotion": "A personal or communal practice fostering love for God, the saints, or specific mysteries of faith.",
    "eucharistic adoration": "The silent worship of Jesus Christ present in the Blessed Sacrament, exposed on the altar.",
    "eucharistic presence": "The doctrine that Christ is truly present—Body, Blood, Soul, and Divinity—in the Eucharist.",
    "feast day": "A liturgical day set aside to honor a saint, mystery, or event in salvation history.",
    "holy communion": "The reception of the Body and Blood of Christ in the Eucharist, uniting the soul to Him.",
    "holy sacrifice": "The Mass, which re-presents Christ’s sacrifice on Calvary in an unbloody manner.",
    "immaculate conception": "The dogma that Mary was preserved free from original sin from the first moment of her existence.",
    "immaculate heart": "The heart of Mary, full of purity, love, and sorrow, venerated especially in reparation for sin.",
    "lamb of god": "A title for Christ who offered Himself as the perfect sacrifice to take away the sins of the world.",
    "litanies": "Structured prayers calling upon the Lord, Our Lady, or the saints with repeated responses.",
    "litany of humility": "A prayer asking for the grace to be freed from pride, self-seeking, and worldly esteem.",
    "liturgical season": "One of the cycles of the Church year—Advent, Christmas, Lent, Easter, or Ordinary Time.",
    "liturgical solemnity": "A high-ranking feast in the Church calendar, often celebrating central mysteries of the faith.",
    "magnificat": "Mary’s canticle of praise to God, expressing her humility and joy in God’s mercy.",
    "mass": "The holy sacrifice instituted by Christ, in which the Eucharist is consecrated and received.",
    "ordinary time": "The liturgical season focusing on the life and teachings of Christ, outside the major feasts.",
    "our father": "The Lord’s Prayer, taught by Christ and central to all Christian prayer.",
    "pentecost": "The feast of the Holy Spirit’s descent upon the Apostles, marking the birth of the Church.",
    "rosary": "A meditative prayer reflecting on the life of Christ and Mary through the repetition of Hail Marys and mysteries.",
    "sacred heart": "The wounded, burning Heart of Jesus—symbol of divine love and mercy for sinners.",
    "saturday devotion": "Special honor given to Our Lady on Saturdays, especially through the First Saturday devotion.",
    "solemnity": "The highest rank of liturgical day, commemorating foundational events or truths of the faith.",
    "sunday": "The Lord’s Day, celebrating the Resurrection and the central mystery of the Christian life.",
    "transubstantiation": "The change by which the bread and wine become the Body and Blood of Christ at Mass.",
    "visitation": "The feast commemorating Mary’s visit to Elizabeth, marked by joy, humility, and mutual faith.",
  },

  // Typological and biblical themes.
  // These meditations draw on typology, where Old Testament figures and events prefigure Christ
  typological: {
    "bread and wine": "Symbols of sacrificial offering and divine communion, prefiguring the Eucharist.",
    "blood and water": "The outpouring from Christ’s side, signifying the sacraments of Eucharist and Baptism.",
    "blood and water from christ's side": "A direct reference to John 19:34, symbolizing the birth of the Church through Christ’s Passion.",
    "blood of the covenant": "The sacrificial blood that seals God's covenant, fulfilled in Christ’s Passion.",
    "bronze serpent lifted up": "A foreshadowing of Christ crucified, who brings healing when looked upon in faith.",
    "covenant": "God’s solemn agreement with His people, fulfilled and renewed in Christ.",
    "daniel 7": "The vision of the ‘Son of Man’ receiving dominion, a prophecy fulfilled in Christ’s kingship.",
    "foot washing": "A type of Christ’s self-emptying love and the call to humble service.",
    "gehenna": "A biblical term used to describe the fate of the damned — symbol of final separation from God.",
    "good samaritan": "A parable prefiguring Christ as the merciful healer of fallen humanity.",
    "high priest": "A foreshadowing of Christ’s mediating role in the New Covenant through His sacrifice.",
    "isaac carrying the wood": "A profound type of Christ carrying the Cross to His own sacrifice.",
    "joseph feeding egypt": "A type of Christ nourishing the world with the Bread of Life.",
    "judas": "A type of betrayal within the sacred circle — a warning against hardened hearts.",
    "lake of fire": "An apocalyptic image of eternal separation from God’s presence — a call to repentance.",
    "levitical priesthood": "The Old Testament priesthood that prefigures Christ’s eternal priesthood.",
    "light from above": "A sign of divine illumination and grace breaking into the world.",
    "lost sheep": "A type of the sinner sought by Christ, the Good Shepherd.",
    "marriage feast of the Lamb": "A symbol of the final union between Christ and His Church.",
    "melchizedek": "The priest-king of Salem, a type of Christ’s eternal priesthood and Eucharistic offering.",
    "moses": "A liberator and lawgiver who prefigures Christ’s deliverance and new law of grace.",
    "paschal lamb": "The slain lamb whose blood saves — a clear type of Christ’s sacrificial death.",
    "prodigal son": "A type of the sinner’s return and the Father’s overwhelming mercy.",
    "promised land": "A type of Heaven, the true rest and inheritance of God’s people.",
    "rejected cornerstone": "A prophecy fulfilled in Christ — rejected by men, chosen by God.",
    "sacrifice": "The repeated Old Covenant sacrifices foreshadow Christ’s one perfect offering.",
    "sheep and goats": "A type of the final judgment separating the just from the unjust.",
    "shepherds": "Types of watchfulness and receptivity, the first to adore Christ at His birth.",
    "sinai": "The mountain where the Law was given — a type of the new covenant fulfilled in Christ.",
    "son of man": "A messianic title from Daniel, used by Jesus to reveal His divine mission.",
    "spiritual captivity": "A type of sin’s bondage, from which Christ frees the soul.",
    "temple": "The dwelling of God among His people — now fulfilled in Christ’s Body and the Church.",
    "temple in heaven": "The eternal sanctuary where Christ intercedes before the Father.",
    "temple veil torn": "The sign of access to God now opened through Christ’s death.",
    "the face of the crucified": "A type of divine love made visible through suffering.",
    "the father running to meet the prodigal": "An image of God’s eagerness to forgive and restore the penitent.",
    "the pierced heart": "A type of the outpouring of divine love through Christ’s suffering.",
    "the return from exile": "A type of spiritual restoration and homecoming through mercy.",
    "veil of the temple": "A barrier symbolizing distance from God, torn at Christ’s death to signify union.",
    "veil of veronica": "A devotional tradition highlighting the imprint of Christ’s face — the image of divine suffering.",
    "vine and branches": "A type of mystical union with Christ, who gives life and fruitfulness to the soul.",
  },

  // Structural themes and formats.
  // These meditations are organized around specific structures, such as the Rosary or Gospel passages
  structural: {
  "anchor image": "A consistent visual theme or image that ties the meditation arc together.",
  "consecration": "Tags meditations centered on formal or implicit acts of consecration to God, Mary, or Christ.",
  "fixed anchor image": "Indicates that a meditation arc uses a single, consistent anchor image across all days.",
  "gospel discourse": "Denotes meditations structured around direct teaching passages of Jesus in the Gospels.",
  "joyful mysteries": "Marks content structured around or inspired by the Joyful Mysteries of the Rosary.",
  "line-by-line meditation": "A slow, textual unpacking of a spiritual text or passage, often sequential.",
  "litany": "Meditations built around the structure of a formal Church litany (e.g., Sacred Heart, Humility).",
  "luke": "Designates that the arc draws specifically from St. Luke’s Gospel.",
  "meditations on divine charity": "Identifies a spiritual sequence explicitly tied to unfolding God’s love.",
  "moral formation": "Tags content focused on practical virtue and character development.",
  "multi-day sequence": "Indicates the arc spans multiple days as a coherent unit (not a standalone).",
  "narrative gospel meditation": "Uses a story or event from Christ’s life as a springboard for meditation.",
  "parable": "Denotes arcs that are structured around the parables of Christ.",
  "pauline theology": "Themes and meditations structured by insights from the writings of St. Paul.",
  "rosary": "Identifies arcs that follow Rosary structure (Joyful, Sorrowful, etc).",
  "rotating anchor images": "The anchor image shifts each day (e.g. different Rosary mysteries).",
  "sacramental theology": "Explores the mystery, grace, and effects of the sacraments.",
  "scripture": "Uses Sacred Scripture as the direct primary reading or organizing structure.",
  "theological + affective blend": "Fuses doctrinal content with affective prayer and emotional engagement.",
  "unified anchor image": "The arc’s days are visually rooted in one continuous image across the sequence.",
  },
};

export default tagDescriptions;
