name: Import metadata to RDS

on:
  push:
    branches: [ main ]
    paths:
      - 'metadata/**'   # Only run when metadata changes

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::756859458263:role/<GHA_OIDC_ROLE_WITH_S3_ECS_PERMS>
          aws-region: us-east-1

      - name: Sync metadata to S3
        run: |
          aws s3 sync metadata s3://spiritual-formation-prod/metadata --delete

      # Option A (recommended): trigger ECS task *directly*
      - name: Run ECS one-off import task
        run: |
          aws ecs run-task \
            --cluster arc-imports-cluster \
            --launch-type FARGATE \
            --task-definition arn:aws:ecs:us-east-1:756859458263:task-definition/spiritual-formation-import-job:1 \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-abc,subnet-def],securityGroups=[sg-123],assignPublicIp=DISABLED}" \
            --count 1 \
            --overrides '{
              "containerOverrides": [{
                "name": "import-runner",
                "environment": [
                  {"name":"S3_BUCKET_NAME","value":"spiritual-formation-prod"},
                  {"name":"AWS_REGION","value":"us-east-1"},
                  {"name":"DJANGO_DB","value":"postgres"},
                  {"name":"HOME","value":"/home/app"}
                ]
              }]
            }'
