name: Tag Format Checker

on:
  workflow_dispatch:
  
  push:
    paths:
      - 'meditations/**/*.md'
  pull_request:
    paths:
      - 'meditations/**/*.md'

jobs:
  tag-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tag format check
        run: |
          pip install pyyaml
          python scripts/check_daily_meditations_tags.py
