name: metadata-sync-staging

on:
  # Build on PRs (from same repo) so reviewers can try the image
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, release/** ]
    paths:
      - 'metadata/**'      # Only run if files in metadata/ change

  # Build on merges to release/* (treat as staging)
  push:
    branches: [ release/** ]
    paths:
      - 'metadata/**'      # Only run if files in metadata/ change

  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  METADATA_BUCKET: spiritual-formation-staging  # make sure this matches the bucket we create in Terraform

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::756859458263:role/spiritual-staging-github-apprepo-metadata
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync metadata to S3
        run: |
          aws s3 sync metadata "s3://${METADATA_BUCKET}/metadata" --delete
