name: metadata-sync-staging

on:
  push:
    branches: [ main, release* ]
    paths: [ 'metadata/**' ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, release* ]
    paths: [ 'metadata/**' ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read



env:
  AWS_REGION: us-east-1
  METADATA_BUCKET: spiritual-formation-staging

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: metadata-sync-staging
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: dorny/paths-filter@v3
        id: pf
        with:
          # detect added/modified/deleted files in metadata/**
          filters: |
            added:
              - added: ['metadata/**']
            modified:
              - modified: ['metadata/**']
            deleted:
              - deleted: ['metadata/**']

      - name: Configure AWS (OIDC)
        if: (steps.pf.outputs.added == 'true' || steps.pf.outputs.modified == 'true' || steps.pf.outputs.deleted == 'true') && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork != true)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::756859458263:role/spiritual-staging-github-apprepo-metadata
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload added/modified files
        if: steps.pf.outputs.added == 'true' || steps.pf.outputs.modified == 'true'
        shell: bash
        env:
          BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          HEAD_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
        run: |
          git diff --name-only --diff-filter=AM "$BASE_SHA" "$HEAD_SHA" -- 'metadata/**' \
          | while IFS= read -r p; do
              aws s3 cp "$p" "s3://${METADATA_BUCKET}/$p" --only-show-errors
            done

      - name: Delete removed files
        if: steps.pf.outputs.deleted == 'true'
        shell: bash
        env:
          BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          HEAD_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
        run: |
          git diff --name-only --diff-filter=D "$BASE_SHA" "$HEAD_SHA" -- 'metadata/**' \
          | while IFS= read -r p; do
              aws s3 rm "s3://${METADATA_BUCKET}/$p" --only-show-errors || true
            done

      - name: Fire single trigger
        if: (steps.pf.outputs.added == 'true' || steps.pf.outputs.modified == 'true' || steps.pf.outputs.deleted == 'true')
        shell: bash
        run: |
          TMP=$(mktemp)
          echo "{\"run_id\":\"${GITHUB_RUN_ID}\",\"sha\":\"${GITHUB_SHA}\",\"ts\":\"$(date -u +%FT%TZ)\"}" > "$TMP"
          aws s3 cp "$TMP" "s3://${METADATA_BUCKET}/metadata/_triggers/${GITHUB_RUN_ID}-${GITHUB_SHA}.json" --only-show-errors
