name: metadata-sync-staging

on:
  push:
    branches: [ main, release/** ]
    paths: [ 'metadata/**' ]
  workflow_dispatch: {}

  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths: [ 'metadata/**' ]

permissions:
  id-token: write
  contents: read

concurrency:
  group: metadata-sync-staging
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  METADATA_BUCKET: spiritual-formation-staging

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::756859458263:role/spiritual-staging-github-apprepo-metadata
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync metadata to S3
        run: aws s3 sync metadata "s3://${METADATA_BUCKET}/metadata" --delete
