name: SMPF Markdown Linter

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-smpf:
    name: Check SMPF Markdown Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run SMPF Linter
        run: python scripts/smpf_linter.py
